var getInnerHTML = function() {
  var d = Math.random();
  var str;
  if (d < 1/4) {
    var jw = chrome.extension.getURL('jw1.jpg');
    str = '<div id="centralNotice" class="expanded"> <style type="text/css"> #centralNotice.collapsed .cn-fundraiser-banner { display: none; } #content a[href^="https://"], .link-https { background-image: none !important; padding: 0 !important; } .cn-fundraiser-banner { position: relative; border: 1px solid silver; background-color: #fbfbfb; margin-bottom: 0.5em !important; padding-top: 1em; padding-bottom: 1em; text-align:center; } .cn-blue-text { font-weight: bold; font-family: Helvetica, Verdana, sans-serif; color: #6e98c2; text-align: center; font-size: 1.3em; } .cn-bold-blue-text { font-size: 2.25em; font-weight: bold; font-family: Helvetica, Arial, sans-serif; color: navy; text-align: center; padding: 0.5em !important; line-height: 1em; } .cn-bottom-right-float { position: absolute; z-index: 1000; right: 1em; bottom: 1em; } a.cn-full-banner-click { display:block; position:relative; height:100%; width:100%; } </style> <style type="text/css"> #centralNotice.collapsed #JA1banner2 { display: none; } #JA1banner2{ position: relative; border: solid 1px silver; background-color: #1e1e1e; height: 172px; background-image: url(' + jw + '); background-position: lefttop; background-repeat: no-repeat; margin-bottom: 0.5em !important; } #JA1banner2-text { padding: .75em 0 .75em 200px !important; overflow: hidden; color: #FFFFFF; font-family: helvetica, arial, monospace; font-weight: normal; text-align: left; font-size: 2.5em; line-height: 1.125em; cursor: pointer; width: auto; background-color: transparent; } #JA1banner2 a:hover { text-decoration: underline; color: #FFFFFF; } #JA1banner2 a { text-decoration: none; color: #FFFFFF; } </style> <div id="JA1banner2"> <a class="variable_lp cn-full-banner-click" href="http://wikimediafoundation.org/w/index.php?title=WMFJA1/en"> <div id="JA1banner2-text"> <span> Please read:<br>A personal appeal from <br> Wikipedia founder Jimmy Wales</span> </div> </a> </div> </div>';
  } else if (1/4 <= d && d < 2/4) {
    var jw = chrome.extension.getURL('jw2.jpg');
    str = '<div id="centralNotice" class="expanded"><style type="text/css"> #centralNotice.collapsed .cn-fundraiser-banner { display: none; } #content a[href^="https://"], .link-https { background-image: none !important; padding: 0 !important; } .cn-fundraiser-banner { position: relative; border: 1px solid silver; background-color: #fbfbfb; margin-bottom: 0.5em !important; padding-top: 1em; padding-bottom: 1em; text-align:center; } .cn-blue-text { font-weight: bold; font-family: Helvetica, Verdana, sans-serif; color: #6e98c2; text-align: center; font-size: 1.3em; } .cn-bold-blue-text { font-size: 2.25em; font-weight: bold; font-family: Helvetica, Arial, sans-serif; color: navy; text-align: center; padding: 0.5em !important; line-height: 1em; } .cn-bottom-right-float { position: absolute; z-index: 1000; right: 1em; bottom: 1em; } a.cn-full-banner-click { display:block; position:relative; height:100%; width:100%; } </style> <style type="text/css"> #centralNotice.collapsed #JA1banner3{ display: none; } #JA1banner3{ position: relative; border: solid 1px silver; background-color: #1e1e1e; height: 172px; background-image: url(' + jw + '); background-position: right top; background-repeat: no-repeat; margin-bottom: 0.5em !important; } #JA1banner3-text { padding: 1.25em 50px .75em .75em !important; overflow: visible; color: #333333; font-family: helvetica, arial, monospace; font-weight: normal; text-align: left; font-size: 2.25em; line-height: 1.125em; cursor: pointer; width: 60%; background-color: transparent; } #JA1banner3 a:hover { text-decoration: underline; color: #333333; } #JA1banner3 a { text-decoration: none; color: #333333; } </style> <div id="JA1banner3"> <a class="variable_lp cn-full-banner-click" href="http://wikimediafoundation.org/w/index.php?title=WMFJA1/en"> <div id="JA1banner3-text"> <span> Please read:<br>A personal appeal from <br> Wikipedia founder Jimmy Wales</span> </div> </a> </div></div>';
  } else if (2/4 <= d && d < 3/4) {
    var bg = chrome.extension.getURL('jw4_bg.jpg');
    var tb = chrome.extension.getURL('jw4_tb.png');
    str = '<div id="centralNotice" class="expanded"> <style type="text/css"> #centralNotice.collapsed .cn-fundraiser-banner { display: none; } #centralNotice a[href^="https://"], .link-https { background-image: none !important; padding: 0 !important; } .cn-fundraiser-banner { position: relative; border: 1px solid silver; background-color: #fbfbfb; margin-bottom: 0.5em !important; padding-top: 1em; padding-bottom: 1em; text-align:center; } .cn-blue-text { font-weight: bold; font-family: Helvetica, Verdana, sans-serif; color: #6e98c2; text-align: center; font-size: 1.3em; } .cn-bold-blue-text { font-size: 2.25em; font-weight: bold; font-family: Helvetica, Arial, sans-serif; color: navy; text-align: center; padding: 0.5em !important; line-height: 1em; } .cn-bottom-right-float { position: absolute; z-index: 1000; right: 1em; bottom: 1em; } a.cn-full-banner-click { display:block; position:relative; height:100%; width:100%; } </style> <style type="text/css"> #centralNotice.collapsed #JA1banner6C { display: none; } #JA1banner6C { position: relative; border: solid 1px silver; background-color: #00324d; height: 172px; background-image: url(' + bg + '); background-position: left top; background-repeat: no-repeat; margin-bottom: 0.5em !important; } #JA1banner6CText { position: absolute; left: 25px; top: 25px; width: 396px; height: 122px; background-image: url(' + tb + '); background-repeat: no-repeat; background-color: transparent; } #JA1banner6C a:hover { text-decoration: underline; color: #FFFFFF; } </style> <div id="JA1banner6C"> <a class="variable_lp cn-full-banner-click" href="http://wikimediafoundation.org/w/index.php?title=WMFJA1/en"> <div id="JA1banner6CText"> </div> </a> </div> </div>';
  } else {
    var tile = chrome.extension.getURL('jw3_tile.png');
    var wales = chrome.extension.getURL('jw3_wales.jpg');
    var text = chrome.extension.getURL('jw3_text.png');
    var button = chrome.extension.getURL('jw3_button.png');
    str = '<div id="centralNotice" class="expanded"><style type="text/css"> #centralNotice.collapsed .cn-fundraiser-banner { display: none; } #content a[href^="https://"], .link-https { background-image: none !important; padding: 0 !important; } .cn-fundraiser-banner { position: relative; border: 1px solid silver; background-color: #fbfbfb; margin-bottom: 0.5em !important; padding-top: 1em; padding-bottom: 1em; text-align:center; } .cn-blue-text { font-weight: bold; font-family: Helvetica, Verdana, sans-serif; color: #6e98c2; text-align: center; font-size: 1.3em; } .cn-bold-blue-text { font-size: 2.25em; font-weight: bold; font-family: Helvetica, Arial, sans-serif; color: navy; text-align: center; padding: 0.5em !important; line-height: 1em; } .cn-bottom-right-float { position: absolute; z-index: 1000; right: 1em; bottom: 1em; } a.cn-full-banner-click { display:block; position:relative; height:100%; width:100%; } </style> <style type="text/css"> #centralNotice.collapsed #JA1banner7Tile{ display: none; } #JA1banner7Tile{ position: relative; border: solid 1px silver; background-color: #010103; height: 172px; background-image: url(' + tile + '); background-position: center top; background-repeat: repeat-x; margin-bottom: 0.5em !important; } #JA1banner7Main{ position: relative; height: 172px; background-image: url(' + wales + '); background-position: left top; background-repeat: no-repeat; margin-bottom: 0.5em !important; } #JA1banner7-text { position: absolute; z-index: 5; left: 205px; top: 45px; height: 84px; background-image: url(' + text + '); width: 404px; background-repeat: no-repeat; background-color: transparent; } #notice-button7 { position: absolute; bottom:60px; right:15px; background-image: url(' + button + '); background-repeat: no-repeat; height: 52px; width: 198px; } </style> <div id="JA1banner7Tile"> <div id="JA1banner7Main"> <a class="variable_lp cn-full-banner-click" href="http://wikimediafoundation.org/w/index.php?title=WMFJA1/en"> <div id="JA1banner7-text"> </div> <div id="notice-button7"> </div> </a> </div> </div></div>';
  }
  return str;
};
